import type { FollowUpQuestion, Source } from '@cargpt/shared';
import type { RawHypothesis } from '../contracts/llm-provider';

/**
 * A verified knowledge base of common vehicle faults.
 * Each hypothesis cites recognized reference sources (no fabricated URLs).
 * This is the retrieval corpus behind free-text diagnosis; a real LLM
 * provider can use the same entries as grounding (RAG) when enabled.
 */
export interface KnowledgeEntry {
  id: string;
  title: string;
  /** Hebrew/English terms & synonyms used for free-text matching. */
  keywords: string[];
  followUps?: FollowUpQuestion[];
  hypotheses: RawHypothesis[];
}

/* ---------- Recognized sources (names only, no invented links) ---------- */
const S = {
  manufacturer: { title: 'מדריך שירות יצרן', publisher: 'מדריך יצרן', type: 'manufacturer' } as Source,
  nhtsa: { title: 'בטיחות רכב ותקלות', publisher: 'NHTSA', type: 'regulator' } as Source,
  motIl: { title: 'תקנות ובטיחות רכב', publisher: 'משרד התחבורה', type: 'regulator' } as Source,
  obd: { title: 'קודי תקלה OBD-II', publisher: 'תקן SAE J1979', type: 'standard' } as Source,
  community: { title: 'מאגר תקלות קהילתי', publisher: 'קהילת CarGPT', type: 'community' } as Source,
  reference: { title: 'מדריך תיקונים מקצועי', publisher: 'ידע מקצועי', type: 'reference' } as Source,
};

const ILS = 'ILS' as const;

/** Universal questions used when the free text doesn't match a specific area. */
export const UNIVERSAL_FOLLOWUPS: FollowUpQuestion[] = [
  {
    id: 'area',
    question: 'באיזה תחום מורגשת הבעיה?',
    options: ['מנוע', 'בלמים', 'היגוי/הגה', 'גיר', 'חשמל/התנעה', 'מיזוג', 'רעש/רעידות', 'צמיגים'],
  },
];

/** Sourced fallback when nothing specific matches — never a dead end. */
export const GENERIC_GUIDANCE: RawHypothesis[] = [
  {
    label: 'מומלץ לבצע סריקת OBD לאבחון מדויק',
    probability: 0.6,
    confidence: 0.4,
    reasoning:
      'כשהתסמינים כלליים, סריקת קודי תקלה (OBD-II) מזהה את מקור הבעיה במדויק לפני החלפת חלקים.',
    price: { low: 100, avg: 200, high: 350, currency: ILS },
    estLaborHours: 0.5,
    riskLevel: 'yellow',
    sources: [S.obd, S.manufacturer],
  },
  {
    label: 'בדיקה חזותית במוסך מוסמך',
    probability: 0.4,
    confidence: 0.35,
    reasoning: 'בדיקה פיזית מאתרת נזילות, בלאי ורכיבים פגומים שלא תמיד מופיעים כקוד תקלה.',
    price: { low: 0, avg: 150, high: 300, currency: ILS },
    estLaborHours: 0.5,
    riskLevel: 'yellow',
    sources: [S.reference, S.community],
  },
];

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    id: 'turning-noise',
    title: 'רעש בפנייה / מהגלגל',
    keywords: ['רעש', 'פנייה', 'פניה', 'סיבוב', 'גלגל', 'המהום', 'רחש'],
    followUps: [
      { id: 'when', question: 'מתי הרעש מופיע?', options: ['רק בפנייה', 'תמיד בנסיעה', 'רק כשקר', 'רק בבלימה'] },
      { id: 'warning-light', question: 'יש נורת תקלה דולקת?', options: ['כן', 'לא', 'לא בטוח'] },
    ],
    hypotheses: [
      {
        label: 'מיסב גלגל',
        probability: 0.8,
        confidence: 0.7,
        reasoning: 'רעש מחזורי שמשתנה עם המהירות/פנייה אופייני לבלאי מיסב גלגל.',
        price: { low: 450, avg: 700, high: 950, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'בולם זעזועים',
        probability: 0.15,
        confidence: 0.5,
        reasoning: 'רעש בפנייה יכול לנבוע גם ממערכת מתלים שחוקה.',
        price: { low: 600, avg: 900, high: 1300, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
      {
        label: 'דיסק/רפידות בלם',
        probability: 0.05,
        confidence: 0.4,
        reasoning: 'פחות סביר, אך רעש הקשור לבלימה מצריך שלילה.',
        price: { low: 400, avg: 650, high: 900, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'red',
        sources: [S.nhtsa, S.manufacturer],
      },
    ],
  },
  {
    id: 'engine-light',
    title: 'נורת מנוע / כשל הצתה',
    keywords: ['נורה', 'מנוע', 'צ׳ק', "צ'ק", 'check', 'נדלק', 'נורית'],
    followUps: [
      { id: 'light-color', question: 'באיזה צבע הנורה?', options: ['כתום', 'אדום', 'מהבהב'] },
      { id: 'behavior', question: 'איך הרכב מתנהג?', options: ['תקין', 'אובדן כוח', 'רעידות', 'עשן'] },
    ],
    hypotheses: [
      {
        label: 'סליל הצתה',
        probability: 0.55,
        confidence: 0.6,
        reasoning: 'נורת מנוע עם רעידות בסרק מצביעה לרוב על כשל בהצתה.',
        price: { low: 250, avg: 450, high: 700, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.obd, S.manufacturer],
      },
      {
        label: 'מצתים',
        probability: 0.3,
        confidence: 0.5,
        reasoning: 'מצתים שחוקים גורמים לבעיות הצתה דומות.',
        price: { low: 200, avg: 350, high: 500, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
      {
        label: 'מזרק דלק',
        probability: 0.15,
        confidence: 0.4,
        reasoning: 'פחות שכיח אך אפשרי בתסמינים דומים.',
        price: { low: 500, avg: 900, high: 1400, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.obd, S.reference],
      },
    ],
  },
  {
    id: 'rough-idle',
    title: 'רעידות בסרק',
    keywords: ['רועד', 'רעידות', 'סרק', 'רטט', 'רועדת'],
    followUps: [{ id: 'cold', question: 'זה קורה רק כשהמנוע קר?', options: ['כן', 'לא', 'תמיד'] }],
    hypotheses: [
      {
        label: 'תושבות מנוע',
        probability: 0.5,
        confidence: 0.55,
        reasoning: 'רעידות בסרק אופייניות לתושבות מנוע שחוקות.',
        price: { low: 400, avg: 750, high: 1200, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'כשל הצתה',
        probability: 0.5,
        confidence: 0.55,
        reasoning: 'רעידות עם חוסר יציבות מנוע יכולות לנבוע מכשל הצתה.',
        price: { low: 250, avg: 450, high: 700, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.obd],
      },
    ],
  },
  {
    id: 'brakes',
    title: 'בלמים',
    keywords: ['בלם', 'בלמים', 'בלימה', 'ברקס', 'חריקה בבלימה', 'רפידות'],
    hypotheses: [
      {
        label: 'רפידות בלם שחוקות',
        probability: 0.7,
        confidence: 0.6,
        reasoning: 'תלונות על בלימה קשורות ברוב המקרים לרפידות שחוקות.',
        price: { low: 300, avg: 550, high: 800, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'red',
        sources: [S.nhtsa, S.manufacturer],
      },
      {
        label: 'דיסקים שחוקים',
        probability: 0.3,
        confidence: 0.5,
        reasoning: 'דיסקים פגומים יכולים לגרום לרעש/רעידות בבלימה.',
        price: { low: 500, avg: 900, high: 1300, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa, S.reference],
      },
    ],
  },
  {
    id: 'overheating',
    title: 'התחממות מנוע',
    keywords: ['חום', 'מתחמם', 'רתיחה', 'טמפרטורה', 'מדחום', 'קירור', 'נוזל קירור', 'מים', 'overheat'],
    hypotheses: [
      {
        label: 'תרמוסטט תקוע',
        probability: 0.4,
        confidence: 0.5,
        reasoning: 'תרמוסטט שנתקע סגור מונע זרימת נוזל קירור וגורם להתחממות.',
        price: { low: 250, avg: 450, high: 700, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'red',
        sources: [S.manufacturer, S.nhtsa],
      },
      {
        label: 'נזילת נוזל קירור',
        probability: 0.35,
        confidence: 0.5,
        reasoning: 'ירידה במפלס הנוזל עקב נזילה גורמת להתחממות מהירה.',
        price: { low: 300, avg: 700, high: 1500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.reference],
      },
      {
        label: 'משאבת מים',
        probability: 0.25,
        confidence: 0.45,
        reasoning: 'משאבת מים תקולה אינה מסחררת את נוזל הקירור כראוי.',
        price: { low: 500, avg: 1000, high: 1800, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'red',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'no-start',
    title: 'הרכב לא מתניע',
    keywords: ['לא מתניע', 'לא נדלק', 'מתנע', 'מצבר', 'בטריה', 'סטרטר', 'לא מתחיל', 'start', 'חשמל', 'התנעה'],
    hypotheses: [
      {
        label: 'מצבר חלש/מרוקן',
        probability: 0.55,
        confidence: 0.6,
        reasoning: 'הסיבה השכיחה ביותר לאי-התנעה, במיוחד בבוקר קר.',
        price: { low: 350, avg: 550, high: 900, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'מתנע (סטרטר)',
        probability: 0.3,
        confidence: 0.5,
        reasoning: 'קליק בודד ללא סיבוב מנוע מצביע לרוב על מתנע תקול.',
        price: { low: 600, avg: 1100, high: 1800, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
      {
        label: 'אלטרנטור',
        probability: 0.15,
        confidence: 0.4,
        reasoning: 'אלטרנטור שאינו טוען מרוקן את המצבר ומונע התנעה.',
        price: { low: 700, avg: 1300, high: 2200, currency: ILS },
        estLaborHours: 2.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'charging',
    title: 'טעינה / אלטרנטור',
    keywords: ['אלטרנטור', 'טעינה', 'נורת מצבר', 'אורות חלשים', 'alternator', 'charge'],
    hypotheses: [
      {
        label: 'אלטרנטור',
        probability: 0.7,
        confidence: 0.55,
        reasoning: 'נורת מצבר דולקת בנסיעה מצביעה על בעיית טעינה מהאלטרנטור.',
        price: { low: 700, avg: 1300, high: 2200, currency: ILS },
        estLaborHours: 2.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.obd],
      },
      {
        label: 'רצועת אלטרנטור',
        probability: 0.3,
        confidence: 0.45,
        reasoning: 'רצועה משוחררת או קרועה מונעת הנעת האלטרנטור.',
        price: { low: 150, avg: 350, high: 600, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'ac',
    title: 'מיזוג אוויר',
    keywords: ['מזגן', 'מיזוג', 'לא מקרר', 'אוויר חם', 'ac', 'קירור', 'גז מזגן'],
    hypotheses: [
      {
        label: 'חוסר גז מזגן',
        probability: 0.5,
        confidence: 0.55,
        reasoning: 'ירידה בגז הקירור היא הסיבה השכיחה למזגן שלא מקרר.',
        price: { low: 150, avg: 300, high: 500, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'קומפרסור מזגן',
        probability: 0.3,
        confidence: 0.45,
        reasoning: 'קומפרסור תקול לא דוחס את הגז ומונע קירור.',
        price: { low: 900, avg: 1800, high: 3000, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'green',
        sources: [S.reference],
      },
      {
        label: 'מאוורר מעבה',
        probability: 0.2,
        confidence: 0.4,
        reasoning: 'מאוורר שאינו פועל פוגע ביעילות הקירור בעצירה.',
        price: { low: 400, avg: 800, high: 1400, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'transmission',
    title: 'תיבת הילוכים / גיר',
    keywords: ['גיר', 'תיבת הילוכים', 'מחליק', 'נתקע', 'אוטומט', 'transmission', 'הילוך'],
    hypotheses: [
      {
        label: 'שמן גיר ישן/חסר',
        probability: 0.45,
        confidence: 0.5,
        reasoning: 'שמן גיר מזוהם או במפלס נמוך גורם להחלקה ולמעברים לא חלקים.',
        price: { low: 400, avg: 700, high: 1200, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
      {
        label: 'סולנואיד/בקר גיר',
        probability: 0.35,
        confidence: 0.45,
        reasoning: 'תקלת בקרה גורמת למעברים קשים או להחלקה.',
        price: { low: 800, avg: 1600, high: 3000, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.obd, S.reference],
      },
      {
        label: 'בלאי מכני בגיר',
        probability: 0.2,
        confidence: 0.4,
        reasoning: 'החלקה מתמשכת עלולה להעיד על בלאי פנימי.',
        price: { low: 2000, avg: 5000, high: 12000, currency: ILS },
        estLaborHours: 8,
        riskLevel: 'red',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'clutch',
    title: 'מצמד',
    keywords: ['מצמד', 'קלאץ', 'clutch', 'מחליק בהילוך'],
    hypotheses: [
      {
        label: 'דיסק מצמד שחוק',
        probability: 0.7,
        confidence: 0.55,
        reasoning: 'עלייה בסיבובים ללא האצה וריח שרוף מעידים על מצמד שחוק.',
        price: { low: 1200, avg: 2200, high: 3500, currency: ILS },
        estLaborHours: 5,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.reference],
      },
      {
        label: 'צילינדר מצמד',
        probability: 0.3,
        confidence: 0.4,
        reasoning: 'תקלה הידראולית גורמת לתחושת דוושה רכה או תפיסה גבוהה.',
        price: { low: 400, avg: 800, high: 1400, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'steering-vibration',
    title: 'רעידות בהגה במהירות',
    keywords: ['רעידות בהגה', 'הגה רועד', 'רועד במהירות', 'איזון', 'רטט בהגה'],
    hypotheses: [
      {
        label: 'חוסר איזון גלגלים',
        probability: 0.6,
        confidence: 0.55,
        reasoning: 'רעידות שמתחילות במהירות מסוימת אופייניות לחוסר איזון.',
        price: { low: 80, avg: 150, high: 250, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'דיסקים עקומים',
        probability: 0.25,
        confidence: 0.45,
        reasoning: 'רעידות שמתגברות בבלימה מעידות על דיסקים עקומים.',
        price: { low: 500, avg: 900, high: 1300, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa],
      },
      {
        label: 'מיסב/מתלים',
        probability: 0.15,
        confidence: 0.4,
        reasoning: 'בלאי במתלים יכול לגרום לרעידות בהגה.',
        price: { low: 500, avg: 1000, high: 1800, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'tires',
    title: 'צמיגים / לחץ אוויר',
    keywords: ['צמיג', 'צמיגים', 'לחץ אוויר', 'שחיקה', 'תקר', 'נורת לחץ', 'tpms', 'tire'],
    hypotheses: [
      {
        label: 'לחץ אוויר לא תקין',
        probability: 0.55,
        confidence: 0.55,
        reasoning: 'לחץ נמוך/גבוה משפיע על אחיזה, בלאי וצריכת דלק.',
        price: { low: 0, avg: 30, high: 60, currency: ILS },
        estLaborHours: 0.2,
        riskLevel: 'yellow',
        sources: [S.motIl, S.manufacturer],
      },
      {
        label: 'שחיקת צמיג',
        probability: 0.3,
        confidence: 0.5,
        reasoning: 'עומק סוליה נמוך מסכן אחיזה ובלימה, ומחייב החלפה.',
        price: { low: 300, avg: 500, high: 900, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'red',
        sources: [S.motIl, S.nhtsa],
      },
      {
        label: 'חיישן לחץ (TPMS)',
        probability: 0.15,
        confidence: 0.4,
        reasoning: 'חיישן תקול מדליק נורית למרות לחץ תקין.',
        price: { low: 150, avg: 300, high: 500, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'exhaust-smoke',
    title: 'עשן מהמפלט',
    keywords: ['עשן', 'מפלט', 'עשן כחול', 'עשן לבן', 'עשן שחור', 'smoke', 'exhaust'],
    followUps: [{ id: 'smoke-color', question: 'באיזה צבע העשן?', options: ['כחול', 'לבן', 'שחור'] }],
    hypotheses: [
      {
        label: 'שריפת שמן (עשן כחול)',
        probability: 0.4,
        confidence: 0.5,
        reasoning: 'עשן כחלחל מעיד על חדירת שמן לתא הבעירה (טבעות/אטמי שסתומים).',
        price: { low: 800, avg: 2500, high: 6000, currency: ILS },
        estLaborHours: 6,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.reference],
      },
      {
        label: 'אטם ראש (עשן לבן)',
        probability: 0.35,
        confidence: 0.45,
        reasoning: 'עשן לבן מתמשך עם ריח מתוק מעיד על חדירת נוזל קירור.',
        price: { low: 1500, avg: 3500, high: 7000, currency: ILS },
        estLaborHours: 8,
        riskLevel: 'red',
        sources: [S.reference],
      },
      {
        label: 'תערובת עשירה (עשן שחור)',
        probability: 0.25,
        confidence: 0.45,
        reasoning: 'עשן שחור מעיד על עודף דלק (חיישנים/מזרקים).',
        price: { low: 400, avg: 900, high: 1800, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.obd],
      },
    ],
  },
  {
    id: 'oil',
    title: 'שמן מנוע / נזילה',
    keywords: ['שמן', 'נזילת שמן', 'נורת שמן', 'לחץ שמן', 'oil', 'טפטוף שמן'],
    hypotheses: [
      {
        label: 'נזילת שמן מאטם',
        probability: 0.5,
        confidence: 0.5,
        reasoning: 'כתמי שמן מתחת לרכב מעידים על אטם שחוק (מכסה שסתומים/אגן).',
        price: { low: 300, avg: 700, high: 1500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.reference],
      },
      {
        label: 'מפלס שמן נמוך',
        probability: 0.3,
        confidence: 0.45,
        reasoning: 'נורת לחץ שמן עלולה לנבוע ממפלס נמוך — יש לעצור ולבדוק מיד.',
        price: { low: 50, avg: 150, high: 300, currency: ILS },
        estLaborHours: 0.3,
        riskLevel: 'red',
        sources: [S.manufacturer],
      },
      {
        label: 'משאבת שמן',
        probability: 0.2,
        confidence: 0.4,
        reasoning: 'לחץ שמן נמוך למרות מפלס תקין עלול להעיד על משאבה חלשה.',
        price: { low: 800, avg: 1600, high: 3000, currency: ILS },
        estLaborHours: 4,
        riskLevel: 'red',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'power-steering',
    title: 'היגוי כבד',
    keywords: ['הגה כבד', 'היגוי כבד', 'הגה קשה', 'power steering', 'שמן הגה', 'היגוי', 'הגה'],
    hypotheses: [
      {
        label: 'שמן היגוי חסר/ישן',
        probability: 0.45,
        confidence: 0.5,
        reasoning: 'מפלס נמוך של שמן היגוי כוח מקשה על הסיבוב ומשמיע רעש.',
        price: { low: 150, avg: 350, high: 600, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
      {
        label: 'משאבת היגוי',
        probability: 0.35,
        confidence: 0.45,
        reasoning: 'משאבה חלשה גורמת להגה כבד במיוחד במהירות נמוכה.',
        price: { low: 700, avg: 1400, high: 2400, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
      {
        label: 'רצועת היגוי',
        probability: 0.2,
        confidence: 0.4,
        reasoning: 'רצועה משוחררת פוגעת בתפקוד ההיגוי.',
        price: { low: 150, avg: 300, high: 550, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'abs',
    title: 'נורת ABS / בקרת יציבות',
    keywords: ['abs', 'נורת abs', 'בקרת יציבות', 'esp', 'traction', 'איי בי אס'],
    hypotheses: [
      {
        label: 'חיישן מהירות גלגל',
        probability: 0.65,
        confidence: 0.5,
        reasoning: 'חיישן ABS מלוכלך/תקול הוא הגורם השכיח לנורת ABS.',
        price: { low: 250, avg: 500, high: 900, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.obd, S.nhtsa],
      },
      {
        label: 'טבעת ABS פגומה',
        probability: 0.35,
        confidence: 0.4,
        reasoning: 'טבעת שיניים פגומה משבשת את קריאת המהירות.',
        price: { low: 300, avg: 700, high: 1300, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'belt-squeal',
    title: 'צפצוף / חריקת רצועה',
    keywords: ['צפצוף', 'חריקה בהתנעה', 'רצועה', 'squeal', 'belt', 'ציוץ'],
    hypotheses: [
      {
        label: 'רצועת אביזרים שחוקה',
        probability: 0.7,
        confidence: 0.55,
        reasoning: 'צפצוף חד בהתנעה או בהאצה אופייני לרצועה שחוקה/רופפת.',
        price: { low: 150, avg: 350, high: 600, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'גלגלת מתח',
        probability: 0.3,
        confidence: 0.4,
        reasoning: 'גלגלת מתח בלויה גורמת לרעש ולשחיקת רצועה מהירה.',
        price: { low: 300, avg: 600, high: 1100, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'fuel-economy',
    title: 'צריכת דלק גבוהה',
    keywords: ['צריכת דלק', 'בזבוז דלק', 'אוכל דלק', 'fuel', 'דלק גבוה'],
    hypotheses: [
      {
        label: 'חיישן חמצן',
        probability: 0.4,
        confidence: 0.45,
        reasoning: 'חיישן חמצן תקול משבש את תערובת הדלק ומעלה צריכה.',
        price: { low: 300, avg: 600, high: 1000, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.obd, S.manufacturer],
      },
      {
        label: 'לחץ אוויר נמוך בצמיגים',
        probability: 0.35,
        confidence: 0.5,
        reasoning: 'לחץ נמוך מעלה התנגדות גלגול וצריכת דלק.',
        price: { low: 0, avg: 30, high: 60, currency: ILS },
        estLaborHours: 0.2,
        riskLevel: 'green',
        sources: [S.motIl],
      },
      {
        label: 'מצתים/מסנן אוויר',
        probability: 0.25,
        confidence: 0.4,
        reasoning: 'רכיבים שחוקים פוגעים ביעילות הבעירה.',
        price: { low: 200, avg: 400, high: 700, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'cv-joint',
    title: 'ציריה / גשר (טק-טק בפנייה)',
    keywords: ['טק טק', 'ציריה', 'גשר', 'קליק בפנייה', 'רעש בפניה חדה', 'cv'],
    hypotheses: [
      {
        label: 'גשר ציריה שחוק',
        probability: 0.75,
        confidence: 0.6,
        reasoning: 'רעש "טק-טק" מחזורי בפנייה חדה אופייני לגשר ציריה שחוק.',
        price: { low: 400, avg: 800, high: 1400, currency: ILS },
        estLaborHours: 2.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.reference],
      },
      {
        label: 'מיסב גלגל',
        probability: 0.25,
        confidence: 0.45,
        reasoning: 'המהום שמשתנה עם המהירות יכול להעיד גם על מיסב.',
        price: { low: 450, avg: 700, high: 950, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'timing-belt',
    title: 'רצועת/שרשרת תזמון',
    keywords: ['רצועת תזמון', 'שרשרת תזמון', 'טיימינג', 'רעש שרשרת', 'timing'],
    hypotheses: [
      {
        label: 'החלפת רצועת תזמון לפי מרווח יצרן',
        probability: 0.6,
        confidence: 0.5,
        reasoning: 'החלפה תקופתית קריטית — קריעה עלולה להרוס את המנוע.',
        price: { low: 1200, avg: 2200, high: 3800, currency: ILS },
        estLaborHours: 5,
        riskLevel: 'red',
        sources: [S.manufacturer],
      },
      {
        label: 'מותחן שרשרת תזמון',
        probability: 0.4,
        confidence: 0.45,
        reasoning: 'שקשוק בהתנעה קרה מצביע על מותחן שרשרת בלוי.',
        price: { low: 800, avg: 1600, high: 2800, currency: ILS },
        estLaborHours: 4,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'turbo',
    title: 'טורבו',
    keywords: ['טורבו', 'שריקה', 'אובדן כוח', 'עשן כחול בהאצה', 'turbo'],
    hypotheses: [
      {
        label: 'דליפת אוויר בצנרת טורבו',
        probability: 0.5,
        confidence: 0.5,
        reasoning: 'ירידת כוח עם שריקה נובעת לרוב מדליפת אוויר בצנרת.',
        price: { low: 300, avg: 700, high: 1500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.obd],
      },
      {
        label: 'טורבו שחוק',
        probability: 0.3,
        confidence: 0.45,
        reasoning: 'עשן כחול ורעש מתכתי מעידים על בלאי בטורבו.',
        price: { low: 2500, avg: 5000, high: 9000, currency: ILS },
        estLaborHours: 6,
        riskLevel: 'red',
        sources: [S.reference],
      },
      {
        label: 'שסתום Wastegate',
        probability: 0.2,
        confidence: 0.4,
        reasoning: 'תקלה בבקרת הלחץ פוגעת בביצועים.',
        price: { low: 600, avg: 1200, high: 2200, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'dpf',
    title: 'מסנן חלקיקים (דיזל / DPF)',
    keywords: ['dpf', 'מסנן חלקיקים', 'פילטר דיזל', 'נורת סינון', 'עשן דיזל'],
    hypotheses: [
      {
        label: 'סתימת מסנן DPF',
        probability: 0.65,
        confidence: 0.5,
        reasoning: 'נסיעות עירוניות קצרות מונעות שריפה עצמית ומובילות לסתימה.',
        price: { low: 400, avg: 1200, high: 3500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.obd],
      },
      {
        label: 'חיישן לחץ DPF',
        probability: 0.35,
        confidence: 0.4,
        reasoning: 'חיישן תקול מדליק נורית למרות מסנן תקין.',
        price: { low: 300, avg: 600, high: 1100, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.obd],
      },
    ],
  },
  {
    id: 'egr',
    title: 'שסתום EGR',
    keywords: ['egr', 'שסתום egr', 'סתימת egr', 'אובדן כוח דיזל'],
    hypotheses: [
      {
        label: 'שסתום EGR סתום',
        probability: 0.7,
        confidence: 0.5,
        reasoning: 'פיח מצטבר וגורם לחוסר יציבות ולאובדן כוח.',
        price: { low: 400, avg: 900, high: 1800, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.obd, S.manufacturer],
      },
      {
        label: 'ניקוי/החלפת EGR',
        probability: 0.3,
        confidence: 0.4,
        reasoning: 'לעיתים ניקוי פותר, אחרת נדרשת החלפה.',
        price: { low: 250, avg: 500, high: 1000, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'green',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'airbag-light',
    title: 'נורת כרית אוויר (SRS)',
    keywords: ['כרית אוויר', 'airbag', 'srs', 'נורת כרית'],
    hypotheses: [
      {
        label: 'מחבר/חיישן SRS רופף',
        probability: 0.6,
        confidence: 0.45,
        reasoning: 'מחבר רופף מתחת למושב הוא גורם שכיח לנורת SRS.',
        price: { low: 200, avg: 500, high: 1000, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.nhtsa, S.manufacturer],
      },
      {
        label: 'רכיב SRS תקול',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'תקלה במערכת עלולה למנוע ניפוח בתאונה — יש לבדוק בהקדם.',
        price: { low: 500, avg: 1200, high: 2500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa],
      },
    ],
  },
  {
    id: 'parking-sensors',
    title: 'חיישני חניה / רוורס',
    keywords: ['חיישני חניה', 'חיישן רוורס', 'צפצוף רוורס', 'parking sensor', 'רוורס'],
    hypotheses: [
      {
        label: 'חיישן חניה תקול',
        probability: 0.7,
        confidence: 0.5,
        reasoning: 'צפצוף רציף או היעדר זיהוי נובעים לרוב מחיישן פגום/מלוכלך.',
        price: { low: 150, avg: 350, high: 700, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
      {
        label: 'חיווט/בקר חיישנים',
        probability: 0.3,
        confidence: 0.4,
        reasoning: 'תקלת חיווט או בקר משביתה את המערכת.',
        price: { low: 300, avg: 600, high: 1200, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'green',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'wipers',
    title: 'מגבים',
    keywords: ['מגבים', 'מגב', 'לא מנקה', 'מנוע מגבים', 'wiper'],
    hypotheses: [
      {
        label: 'גומיות מגב שחוקות',
        probability: 0.6,
        confidence: 0.55,
        reasoning: 'מריחה ופסים על השמשה נגרמים מגומיות בלויות.',
        price: { low: 40, avg: 100, high: 200, currency: ILS },
        estLaborHours: 0.2,
        riskLevel: 'yellow',
        sources: [S.motIl],
      },
      {
        label: 'מנוע/מנגנון מגבים',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'מגבים שאינם זזים מצביעים על מנוע או מנגנון תקול.',
        price: { low: 300, avg: 600, high: 1100, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'windows',
    title: 'חלונות חשמליים',
    keywords: ['חלון חשמלי', 'חלון תקוע', 'מנוע חלון', 'window', 'שמשה לא עולה'],
    hypotheses: [
      {
        label: 'מנגנון מרים חלון',
        probability: 0.6,
        confidence: 0.5,
        reasoning: 'חלון שנתקע או יורד לבד מצביע על מנגנון שבור.',
        price: { low: 300, avg: 600, high: 1100, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'green',
        sources: [S.reference],
      },
      {
        label: 'מתג/מנוע חלון',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'חוסר תגובה מהמתג מעיד על מתג או מנוע תקול.',
        price: { low: 200, avg: 450, high: 900, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'central-locking',
    title: 'נעילה מרכזית / שלט',
    keywords: ['נעילה מרכזית', 'שלט לא עובד', 'לא ננעל', 'central lock', 'שלט רכב'],
    hypotheses: [
      {
        label: 'סוללת שלט',
        probability: 0.5,
        confidence: 0.55,
        reasoning: 'הגורם השכיח ביותר לשלט שלא מגיב.',
        price: { low: 20, avg: 40, high: 80, currency: ILS },
        estLaborHours: 0.1,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
      {
        label: 'אקטואטור נעילה בדלת',
        probability: 0.3,
        confidence: 0.4,
        reasoning: 'דלת בודדת שלא ננעלת מצביעה על אקטואטור.',
        price: { low: 250, avg: 500, high: 900, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'green',
        sources: [S.reference],
      },
      {
        label: 'תכנות שלט מחדש',
        probability: 0.2,
        confidence: 0.35,
        reasoning: 'לעיתים נדרש כיול/תכנות מחדש של השלט.',
        price: { low: 100, avg: 250, high: 500, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'battery-drain',
    title: 'מצבר מתרוקן בלילה',
    keywords: ['מצבר מתרוקן', 'מתרוקן בלילה', 'דליפת זרם', 'parasitic'],
    hypotheses: [
      {
        label: 'צריכת זרם טפילית',
        probability: 0.55,
        confidence: 0.45,
        reasoning: 'רכיב שנשאר פעיל מרוקן את המצבר בלילה — נדרש איתור.',
        price: { low: 250, avg: 500, high: 1000, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.reference, S.obd],
      },
      {
        label: 'מצבר בסוף חיים',
        probability: 0.45,
        confidence: 0.5,
        reasoning: 'מצבר ישן מאבד יכולת אגירה במיוחד בקור.',
        price: { low: 350, avg: 550, high: 900, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'ac-smell',
    title: 'ריח רע מהמזגן',
    keywords: ['ריח מהמזגן', 'ריח עובש', 'ריח רע במזגן', 'ריח לח', 'מזגן', 'ריח'],
    hypotheses: [
      {
        label: 'עובש במאייד/מסנן',
        probability: 0.7,
        confidence: 0.55,
        reasoning: 'לחות מצטברת מגדלת חיידקים ועובש שגורמים לריח.',
        price: { low: 150, avg: 300, high: 600, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'green',
        sources: [S.manufacturer, S.community],
      },
      {
        label: 'מסנן אבקה סתום',
        probability: 0.3,
        confidence: 0.45,
        reasoning: 'מסנן תא נוסעים סתום מחזיק ריחות ולחות.',
        price: { low: 80, avg: 180, high: 350, currency: ILS },
        estLaborHours: 0.5,
        riskLevel: 'green',
        sources: [S.manufacturer],
      },
    ],
  },
  {
    id: 'burning-smell',
    title: 'ריח שרוף',
    keywords: ['ריח שרוף', 'ריח חריכה', 'ריח שריפה'],
    hypotheses: [
      {
        label: 'בלמים/מצמד מתחממים',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'ריח חריכה חריף עלול לנבוע מבלמים תפוסים או ממצמד מחליק — יש לעצור ולבדוק.',
        price: { low: 300, avg: 700, high: 1400, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa, S.reference],
      },
      {
        label: 'שמן על מנוע חם',
        probability: 0.35,
        confidence: 0.4,
        reasoning: 'נזילת שמן קלה על חלקים חמים יוצרת ריח.',
        price: { low: 300, avg: 700, high: 1500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'yellow',
        sources: [S.manufacturer],
      },
      {
        label: 'רכיב חשמלי',
        probability: 0.25,
        confidence: 0.35,
        reasoning: 'ריח פלסטיק שרוף מחייב בדיקה מיידית של חשמל.',
        price: { low: 250, avg: 600, high: 1500, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa],
      },
    ],
  },
  {
    id: 'fuel-smell',
    title: 'ריח דלק',
    keywords: ['ריח דלק', 'ריח בנזין', 'נזילת דלק', 'ריח סולר'],
    hypotheses: [
      {
        label: 'נזילה בצנרת/חיבור דלק',
        probability: 0.55,
        confidence: 0.45,
        reasoning: 'ריח דלק חזק מסכן בטיחות — יש לבדוק דליפה בהקדם.',
        price: { low: 300, avg: 800, high: 1800, currency: ILS },
        estLaborHours: 2,
        riskLevel: 'red',
        sources: [S.nhtsa, S.reference],
      },
      {
        label: 'פקק דלק/מערכת אידוי (EVAP)',
        probability: 0.45,
        confidence: 0.4,
        reasoning: 'פקק דלק לא אטום או תקלת EVAP גורמים לריח ולנורת מנוע.',
        price: { low: 100, avg: 300, high: 800, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.obd],
      },
    ],
  },
  {
    id: 'handbrake',
    title: 'בלם יד',
    keywords: ['בלם יד', 'בלם חניה', 'handbrake', 'בלם יד חלש'],
    hypotheses: [
      {
        label: 'כיוון כבל בלם יד',
        probability: 0.6,
        confidence: 0.5,
        reasoning: 'כבל מתמתח עם הזמן — כיוון פותר לרוב.',
        price: { low: 150, avg: 300, high: 600, currency: ILS },
        estLaborHours: 1,
        riskLevel: 'yellow',
        sources: [S.motIl, S.manufacturer],
      },
      {
        label: 'רפידות/מנגנון אחורי',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'בלאי במנגנון האחורי פוגע באחיזת בלם היד.',
        price: { low: 300, avg: 600, high: 1100, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
  {
    id: 'suspension-squeak',
    title: 'חריקת מתלים בבליטות',
    keywords: ['חריקה בבליטות', 'חריקת מתלים', 'רעש בבליטות', 'טרטור בכביש', 'נקישות במתלים', 'מתלים', 'בליטה'],
    hypotheses: [
      {
        label: 'תותבים/מתלים שחוקים',
        probability: 0.6,
        confidence: 0.5,
        reasoning: 'רעש בבליטות אופייני לתותבי גומי או מתלים בלויים.',
        price: { low: 400, avg: 900, high: 1800, currency: ILS },
        estLaborHours: 3,
        riskLevel: 'yellow',
        sources: [S.manufacturer, S.reference],
      },
      {
        label: 'גומיות מוט מייצב',
        probability: 0.4,
        confidence: 0.4,
        reasoning: 'גומיות מוט מייצב שחוקות משמיעות נקישות.',
        price: { low: 200, avg: 450, high: 800, currency: ILS },
        estLaborHours: 1.5,
        riskLevel: 'yellow',
        sources: [S.reference],
      },
    ],
  },
];
